Div by zero bug
lambdaclass/cairo-vm pull request #1367
Opened 2023-08-09 18:20 UTC by pefontana

# TITLE

## Description

Description of the pull request changes and motivation.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

2023-08-09 20:22 UTC, Oppen requested changes
LGTM, but we need tests for the failing cases as reported by Codecov.

2023-08-10 20:02 UTC, pefontana commented
> LGTM, but we need tests for the failing cases as reported by Codecov.

Nice catch @Oppen!!

I remove both of that checks because they were unreacheble  
[0cfcf7b](https://github.com/lambdaclass/cairo-vm/pull/1367/commits/0cfcf7bd8ed31e7dc0f147992999d8195ae2ece0) has a previous check

[2766a75](https://github.com/lambdaclass/cairo-vm/pull/1367/commits/2766a75e260e7ac0d7d8b63d9d435d4d76a9e3be) Gets the values from a constant defined in the https://github.com/starkware-libs/cairo-lang/blob/0614f265421735bbb567d9b5897791a51b3705de/src/starkware/cairo/common/math.cairo#L156 library

2023-08-10 20:12 UTC, juanbono approved these changes

2023-08-10 20:12 UTC, matias-gonz approved these changes

2023-08-10 20:23 UTC, Oppen approved these changes

2023-08-10 23:45 UTC, merged