Fix air parsing
lambdaclass/cairo-vm pull request #1439
Opened 2023-09-06 14:24 UTC by Juan-M-V

# Fix air parsing

## Description

Change the `PublicInput` serde parsing to match cairo-lang 0.12.2 output

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

2023-09-06 14:26 UTC, fmoletta approved these changes

2023-09-07 19:02 UTC, pefontana requested changes

2023-09-07 19:02 UTC, pefontana commented on vm/src/air_public_input.rs
> +    #[serde(rename = "dynamic_params")]
We should merge this change into main

2023-09-07 19:10 UTC, Juan-M-V commented on vm/src/air_public_input.rs
> +    #[serde(rename = "dynamic_params")]
Rebased!

2023-09-13 18:12 UTC, pefontana approved these changes

2023-09-13 19:54 UTC, merged