Feature: deserialize AIR private input
lambdaclass/cairo-vm pull request #1589
Opened 2024-01-22 11:24 UTC by odesenfans

Added an implementation of `From<AirPrivateInputSerializable>` for AirPrivateInput, making it easier to interact with already generated private inputs.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

2024-01-22 11:54 UTC, odesenfans commented
On a related topic, I do think it would make sense to have `AirPrivateInput` to be a struct instead of a hashmap as it would make it easier to use. `AirPrivateInputSerializable` could then contain an `AirPrivateInput` field (+ `serde(flatten)`).

Any thoughts?

2024-01-22 15:21 UTC, Oppen approved these changes

2024-01-22 15:22 UTC, Oppen requested changes
Any tests for this?

2024-01-31 22:05 UTC, Oppen submitted a review, later dismissed

2024-02-02 15:24 UTC, fmoletta approved these changes

2024-02-02 20:44 UTC, pefontana approved these changes

2024-02-02 20:45 UTC, pefontana commented
@odesenfans Here too, just merge conflicts and we will merge it!

2024-02-14 22:22 UTC, pefontana approved these changes

2024-02-20 21:38 UTC, pefontana commented
@odesenfans Could you merge main?

2024-02-20 21:39 UTC, pefontana commented
@odesenfans were you able to merge main?

2024-02-21 22:52 UTC, odesenfans commented
Hey @pefontana , sorry I was busy with something else. I just rebased the branch.

2024-02-22 15:56 UTC, merged