New tracer pr
lambdaclass/cairo-vm pull request #1643
Opened 2024-03-02 08:01 UTC by apoorvsadana

Description
- Track the ap, fp, pc and the state of the memory in each step of the execution.
- A new crate cairo-vm-tracer which starts a server on the localhost where you can see an web UI. The UI allows you to interact with your Cairo programs and see what's happening inside the VM.
- Most functionality in existing crates has been put behind feature flags with_tracer and tracer

2024-03-05 13:24 UTC, fmoletta commented on docs/tracer/README.md
> +> The `--memory_file` and `--trace_file` arguments are compulsary at the moment as the current code relocates the memory and trace only when these arguments are supplied. However, edits can be made i
```suggestion
> The `--memory_file` and `--trace_file` arguments are compulsory at the moment as the current code relocates the memory and trace only when these arguments are supplied. However, edits can be made in future versions to relocate if only the `--tracer` option is specified.
```
Typo

2024-03-05 13:27 UTC, fmoletta commented on docs/tracer/README.md
> +> The `--memory_file` and `--trace_file` arguments are compulsary at the moment as the current code relocates the memory and trace only when these arguments are supplied. However, edits can be made i
Also, this requirement can be removed by setting the `trace_enabled` & `relocate_mem` flags to true when creating the `CairoRunConfig` in the `run` function of the vm's cli crate.

2024-03-05 13:37 UTC, fmoletta commented on cairo-vm-cli/src/main.rs
> +    tracer: Option<bool>,
Could we simplify this to `bool`?

2024-03-05 22:15 UTC, pefontana requested changes
Amaizing @apoorvsadana !!!!
I try it and works perfect!
Just some points:
* Run the make clippy command that is failing in the CI
* Is necessary to push the .idea folder, if you cant, can we move it inside cairo-vm-tracer/

2024-03-07 07:42 UTC, apoorvsadana commented on cairo-vm-cli/src/main.rs
> +    tracer: Option<bool>,
fixed

2024-03-08 17:46 UTC, pefontana approved these changes
NICEEEEEEE!

2024-03-08 18:42 UTC, fmoletta approved these changes
🚀

2024-03-08 19:51 UTC, merged