Add option to pass Sierra programs to cairo1-run
lambdaclass/cairo-vm pull request #1719
Opened 2024-04-16 18:44 UTC by fmoletta

Mirrors #1544 + Adds some fixes

2024-04-16 20:42 UTC, juanbono approved these changes

2024-04-18 18:14 UTC, pefontana requested changes
Nice @fmoletta !
Just one question, I am getting an error when trying to execute .sierra programs
```
➜  cairo1-run git:(accept-sierra-cairo1-run) ✗ cargo run poseidon.json.sierra --layout all_cairo
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `/Users/peter/repos/cairo-vm/target/debug/cairo1-run poseidon.json.sierra --layout all_cairo`
Error: SierraCompilation("Only files with .cairo extension can be compiled.")
```
I compiled the sierra with cairo compiler v2.6.3
```
cargo run --bin cairo-compile -- --single-file ../cairo-vm/cairo_programs/cairo-1-programs/poseidon.cairo ../cairo-vm/cairo1-run/poseidon.json.sierra --replace-ids
```

Also, do you have a scarb project which I can test to execute?

2024-04-18 18:56 UTC, fmoletta commented
> Nice @fmoletta ! Just one question, I am getting an error when trying to execute .sierra programs
> 
> ```
> ➜  cairo1-run git:(accept-sierra-cairo1-run) ✗ cargo run poseidon.json.sierra --layout all_cairo
>     Finished dev [unoptimized + debuginfo] target(s) in 0.09s
>      Running `/Users/peter/repos/cairo-vm/target/debug/cairo1-run poseidon.json.sierra --layout all_cairo`
> Error: SierraCompilation("Only files with .cairo extension can be compiled.")
> ```
> 
> I compiled the sierra with cairo compiler v2.6.3
> 
> ```
> cargo run --bin cairo-compile -- --single-file ../cairo-vm/cairo_programs/cairo-1-programs/poseidon.cairo ../cairo-vm/cairo1-run/poseidon.json.sierra --replace-ids
> ```
> 
> Also, do you have a scarb project which I can test to execute?

Compilation done by scarb  and by 

> Nice @fmoletta ! Just one question, I am getting an error when trying to execute .sierra programs
> 
> ```
> ➜  cairo1-run git:(accept-sierra-cairo1-run) ✗ cargo run poseidon.json.sierra --layout all_cairo
>     Finished dev [unoptimized + debuginfo] target(s) in 0.09s
>      Running `/Users/peter/repos/cairo-vm/target/debug/cairo1-run poseidon.json.sierra --layout all_cairo`
> Error: SierraCompilation("Only files with .cairo extension can be compiled.")
> ```
> 
> I compiled the sierra with cairo compiler v2.6.3
> 
> ```
> cargo run --bin cairo-compile -- --single-file ../cairo-vm/cairo_programs/cairo-1-programs/poseidon.cairo ../cairo-vm/cairo1-run/poseidon.json.sierra --replace-ids
> ```
> 
> Also, do you have a scarb project which I can test to execute?

 `scarb build` and `cairo-compile` yield different compiled sierra file formats, thats why it fails.
 Creating a project using `scarb init` creates a scarb project with a fibonacci code

2024-04-18 21:35 UTC, pefontana approved these changes

2024-04-18 21:36 UTC, pefontana commented
> > Nice @fmoletta ! Just one question, I am getting an error when trying to execute .sierra programs
> > ```
> > ➜  cairo1-run git:(accept-sierra-cairo1-run) ✗ cargo run poseidon.json.sierra --layout all_cairo
> >     Finished dev [unoptimized + debuginfo] target(s) in 0.09s
> >      Running `/Users/peter/repos/cairo-vm/target/debug/cairo1-run poseidon.json.sierra --layout all_cairo`
> > Error: SierraCompilation("Only files with .cairo extension can be compiled.")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I compiled the sierra with cairo compiler v2.6.3
> > ```
> > cargo run --bin cairo-compile -- --single-file ../cairo-vm/cairo_programs/cairo-1-programs/poseidon.cairo ../cairo-vm/cairo1-run/poseidon.json.sierra --replace-ids
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, do you have a scarb project which I can test to execute?
> 
> `scarb build` and `cairo-compile` yield different compiled sierra file formats, thats why it fails. Creating a project using `scarb init` creates a scarb project with a fibonacci code

Great!
Thanks fede

2024-04-19 21:51 UTC, merged