fix: cairo1-run array argument's length can not be less than 2
lambdaclass/cairo-vm pull request #1737
Opened 2024-04-26 08:31 UTC by catusax

# fix: cairo1-run array argument's length can not be less than 2

## Description

if the program has an argument which is an empty array or the length is 1, cairo1-run fails with error:

```
thread 'main' panicked at cairo1-run/src/main.rs:73:78:
called `Result::unwrap()` on an `Err` value: FromStrError
```

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

2024-04-26 14:04 UTC, fmoletta approved these changes
Thanks for the fix! Please add this PR to the CHANGELOG.md file so we can record the changes!

2024-04-26 15:19 UTC, catusax commented
> Thanks for the fix! Please add this PR to the CHANGELOG.md file so we can record the changes!

CHANGELOG has been updated. please check again

2024-04-26 18:00 UTC, fmoletta commented on CHANGELOG.md
> +
We put the latest changes at the top of the list, could you move it?

2024-04-29 13:23 UTC, fmoletta approved these changes

2024-05-07 14:23 UTC, juanbono approved these changes

2024-05-07 20:27 UTC, pefontana approved these changes

2024-05-07 20:35 UTC, juanbono requested changes
can you provide an example program where you need to pass less than 2 args?

2024-05-08 02:27 UTC, catusax commented
@juanbono tests has been added

2024-05-08 14:28 UTC, juanbono approved these changes

2024-05-09 03:11 UTC, merged