Don't validate memory values
lambdaclass/cairo-vm pull request #1783
Opened 2024-06-04 18:31 UTC by Alon-Ti

Remove validation of values in CairoPie Memory.

2024-06-05 21:07 UTC, juanbono requested changes
Can you add some tests to this?

2024-06-06 09:14 UTC, Alon-Ti commented
@juanbono, I want to add a pathological CairoPie end to end test that will cover this and the previous issue against python VM output (see slack), I can do that once #1781 is merged.

2024-06-09 15:08 UTC, Alon-Ti commented
@juanbono I amended an existing test to cover this, will add a test CairoPie with all the edge cases once I'm sure all our test CairoPies run.

2024-06-10 13:16 UTC, fmoletta commented on cairo_programs/relocate_segments.cairo
> +    assert temporary_array[1] = cast(array, felt) + 100;
Could we have this as a separate test instead?

2024-06-15 17:21 UTC, Oppen approved these changes

2024-06-19 18:55 UTC, juanbono approved these changes

2024-06-19 19:11 UTC, fmoletta approved these changes

2024-06-19 19:28 UTC, merged