stavbe: change AirPrivateInputSerializable fields to public
lambdaclass/cairo-vm pull request #1900
Opened 2024-12-24 08:51 UTC by Stavbe

Change AirPrivateInputSerializable fields to be public, so I can use this struct.

2025-01-05 08:27 UTC, Stavbe commented
Hey :)
I actually need the trace and mem ...

On Fri, Jan 3, 2025 at 5:54 PM Gabriel Bosio ***@***.***>
wrote:

> Hi @Stavbe <https://github.com/Stavbe>! You can convert
> AirPrivateInputSerializable into an AirPrivateInput and then get each
> builtin, for example to get Pedersen:
>
> fn get_pedersen(serializable: AirPrivateInputSerializable) -> Some(Vec<PrivateInput>>) {
>   let air_private_input: AirPrivateInput = serializable.into();
>   air_private_input.0.get(&BuiltinName::pedersen)}
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lambdaclass/cairo-vm/pull/1900#issuecomment-2569453020>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BISYNVSWEM2UIJFVJS6W53D2I2XDJAVCNFSM6AAAAABUEMDEAKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRZGQ2TGMBSGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-07 13:35 UTC, gabrielbosio commented
Ok, I'm trying to get a bit more of context here so what's the use case here? Because when calling `AirPrivateInput::to_serializable` one passes both trace and mem paths: https://github.com/lambdaclass/cairo-vm/blob/259487e5c12fe1fd5912ea540b075a5f4a98456a/vm/src/air_private_input.rs#L154-L158

2025-01-23 08:11 UTC, Stavbe commented
?

On Tue, Jan 7, 2025 at 3:40 PM Stav Beno ***@***.***> wrote:

> The context is that I am trying to read the air_private_input.json, which
>> contains the mem and trace values. I want to deserialize it into the
>> same struct it was created from, instead of creating a similar one in our
>> repository.Message ID: ***@***.***
>> .com>
>>
>

2025-02-03 10:20 UTC, Stavbe reviewed
Sorry, I missed that response.  
Yes, the JSON file (which was created after calling `to_serializable`) contains the `mem` and `trace`.  
Now, when trying to read it (`private.json`), I need to define a new struct to use those fields, which is redundant.  
For example, I read `pub.json` into the `pub struct PublicInput<'a>`.

> *[Reviewable](https://reviewable.io/reviews/lambdaclass/cairo-vm/1900#-:-OIAHLuz2ifTKuivTg0s:b3643hu)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @fmoletta, @gabrielbosio, @igaray, @juanbono, @Oppen, and @pefontana)



<!-- Sent from Reviewable.io -->

2025-03-10 15:31 UTC, JulianGCalderon reviewed
Hi @Stavbe! Would exposing only `trace_path` and `memory_path`suffice? Or maybe we could add getter methods (i.e `get_trace_path()`).

2025-03-11 15:33 UTC, Stavbe reviewed
Yes. that could work. Fixed :)

> *[Reviewable](https://reviewable.io/reviews/lambdaclass/cairo-vm/1900#-:-OL4p_hH6tcic-kvyuFx:b3of0le)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @fmoletta, @gabrielbosio, @igaray, @juanbono, @noaov1, @Oppen, @pefontana, and @yuvalsw)



<!-- Sent from Reviewable.io -->

2025-03-11 17:32 UTC, JulianGCalderon approved these changes

2025-03-16 14:44 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lambdaclass/cairo-vm/1900#-:-OLUPVxQ3cjvq--Le0cl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @fmoletta, @gabrielbosio, @igaray, @juanbono, @noaov1, @Oppen, and @pefontana)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/lambdaclass/cairo-vm/1900#-OLUPUJfDUMyCPS8C_t2:-OLUPUJg3nUyCqKkuLQa:b9kq1g3):*
needs rebase?



_Code quote:_
```
New commits in r2 on 11/03/2025 at 18:49, probably rebased from r1:
- 61a1c75: stavbe: change AirPrivateInputSerializable fields to public

New commits in r3 on 16/03/2025 at 15:52:
- fda1f4c: Merge branch 'main' into stavbe/air-private-input-fields-to-pub
```


<!-- Sent from Reviewable.io -->

2025-03-17 08:24 UTC, Stavbe reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lambdaclass/cairo-vm/1900)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fmoletta, @gabrielbosio, @igaray, @juanbono, @noaov1, @Oppen, and @pefontana)



<!-- Sent from Reviewable.io -->

2025-03-17 13:30 UTC, gabrielbosio requested changes

2025-03-17 13:30 UTC, gabrielbosio commented on vm/src/air_private_input.rs
> +    pub memory_path: String,
If the idea is to read these fields and to not write them, I think it would be better to add getters for these fields instead of making them public

2025-03-17 14:47 UTC, Stavbe commented on vm/src/air_private_input.rs
> +    pub memory_path: String,
It wouldn't work because I read it from json file.

2025-03-17 14:59 UTC, gabrielbosio commented on vm/src/air_private_input.rs
> +    pub memory_path: String,
I'm not completely sure how reading the struct from a json file restricts implementing getters instead of making these fields public.
Let me rephrase my suggestion just in case. For example, instead of accessing these fields like this:

```rust
let trace_path = air_private_input_serializable.trace_path;
let memory_path = air_private_input_serializable.memory_path;
```

Shouldn't this also work?

```rust
let trace_path = air_private_input_serializable.get_trace_path();
let memory_path = air_private_input_serializable.get_memory_path();
```

2025-03-17 15:09 UTC, Stavbe commented on vm/src/air_private_input.rs
> +    pub memory_path: String,
Before being able to call the getter, you need to construct the sturct from the json: 
`fn deserialize_inputs<'a>(
    public_input_string: &'a str,
    private_input_string: &'a str,
) -> Result<(PublicInput<'a>, PrivateInput), VmImportError> {
    {
        Ok((
            sonic_rs::from_str(public_input_string)?,
            sonic_rs::from_str(private_input_string)?,
        ))
    }
    #[cfg(not(feature = "std"))]
    {
        Ok((
            serde_json::from_str(public_input_string)?,
            serde_json::from_str(private_input_string)?,
        ))
    }
`

2025-03-17 15:40 UTC, gabrielbosio commented on vm/src/air_private_input.rs
> +    pub memory_path: String,
Ok, but if you make `trace_path` and `memory_path` public, wouldn't you also need to construct the struct from the json?

2025-03-30 11:22 UTC, closed without merging